import "./my-info.css";

export const metadata = {
  title: "Empathy Diary",
  description: "Generated by create next app",
};

export default function MyInfoPageLayout({ children }) {
    return (
    <div>
        <div className="my-info-contents">
          {children}
        </div>
    </div>
  );
}
