import "./complete.css";

export const metadata = {
  title: "Empathy Diary",
  description: "Generated by create next app",
};

export default function ProfileCompletePageLayout({ children }) {
    return (
    <div>
        <div className="profile-complete-contents">
          {children}
        </div>
    </div>
  );
}
