import "./diary-list.css";
import DiaryListNavBar from './diaryListNavBar.js';

export const metadata = {
  title: "Empathy Diary",
  description: "Generated by create next app",
};

export default function DiaryListPageLayout({ children }) {
    return (
    <div>
        <DiaryListNavBar />
      {children}
    </div>
  );
}
