import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      <div class="container">
        {children}
      </div>
      </body>
    </html>
  );
}
