import "./main-page.css";
import MainNavBar from './mainNavBar.js';

export const metadata = {
  title: "Empathy Diary",
  description: "Generated by create next app",
};

export default function MainPageLayout({ children }) {
    const nickname = "윤빈";

    return (
    <div>
      <div className="top-container">
        <p className="welcome"><span>{nickname}</span>님,<br></br>좋은 하루 되세요!</p>
        <MainNavBar />
      </div>
      {children}
    </div>
  );
}
