import './write.css';

export const metadata = {
    title: "Empathy Diary",
    description: "Generated by create next app",
  };

export default function WriteLayout({ children }) {
    return (
    <div className="write-container">
        {children}
    </div>
  );
}

