import "./profile.css";
import ProfileNavBar from './profileNavBar.js';

export const metadata = {
  title: "Empathy Diary",
  description: "Generated by create next app",
};

export default function ProfliePageLayout({ children }) {
    return (
    <div>
        <ProfileNavBar />
        <div className="profile-contents">
          {children}
        </div>
    </div>
  );
}
