import "./collected.css";

export const metadata = {
  title: "Empathy Diary",
  description: "Generated by create next app",
};

export default function CollectedLayout({ children }) {
    return (
    <div>
      {children}
    </div>
  );
}
