import './chatting-room.css';

export const metadata = {
    title: "Empathy Diary",
    description: "Generated by create next app",
  };

export default function ChattingRoomLayout({ children }) {
    return (
    <div className="chatting-room-container">
        {children}
    </div>
  );
}

